version: '3.4'
services:
  gg: &gg
    image: gg:0.0.1-development
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: sandbox-env
      args:
        UBUNTU_VERSION: '18.04'
    volumes:
      - .:/app/gg:cached
      - ~/.ssh:/root/.ssh:ro
    tmpfs:
      - /tmp
    environment:
      - HISTFILE=/bundle/.bash_history
      - PRY_HISTFILE=/bundle/.pry_history
      - GG_MODELPATH=/app/gg/src/models/wrappers
    env_file:
      - .env
    networks:
      default:
  runner:
    <<: *gg
    entrypoint: /bin/bash
volumes:
  gg:
networks:
  default:
