#!/bin/bash -exf

if [ $# -lt 1 ]; then
  echo "Usage: $(basename $0) DIRECTORY [FILTERS]"
  exit 1
fi

SRCDIR=$1
FILTERS_FILE=$2
NPROC=$(($(nproc)*2))

# HACK make sure gg dir is discoverable
gg-infer sh -c ':'

FIND_CMD=()

if [ ! -z "${FILTERS_FILE}" ]; then
  while read -r FILE
  do
    if [ ${#FIND_CMD[@]} -gt 0 ]; then
      FIND_CMD+=("-o")
    fi
    FIND_CMD+=("-ipath" "$FILE")
  done <${FILTERS_FILE}
else
  FIND_CMD=("-ipath" '*')
fi

function collect_directory {
  find ${SRCDIR} -type f \( ${FIND_CMD[@]} \) | xargs -P ${NPROC} -I% -- gg-collect "%"
}

collect_directory
